### ISSUE TITLE
Stepwise setup of PVA analyses

### ISSUE THREAD

**Issue by ChloeRN** [TaeKP/OpenCR_script#2]
Following up from our discussion today, we will continue expanding on the PVA for fishing cat.
Currently, it employs the simplest model for population dynamics over 2-year time steps, which uses estimates of population growth rate (lambda) and does not include any age structure: 

N[t+2] = N[t] * lambda[t]

Uncertainty in parameter estimates is not completely included yet.

We will expand the model through the following steps: 

- [ ] Implement uncertainty on all parameters in simplest model
- [ ] Change to "Vital rates, no age structure" model, keep 2 year interval
- [ ] Reduce time interval to 1 year
- [ ] Implement "Vital rates, with age structure" model, 1 year interval only

------------------------------------------------------------------------------------
These steps are the bare minimum we need to do to meet the objectives. 
The additional steps below are optional/bonus:
------------------------------------------------------------------------------------

- [ ] Collate data on female/kitten observations
- [ ] Partition recruitment rate into litter size (LS), breeding probability (pB), and early survival (S0)

In the comments below, I summarise additional thoughts, equations, and instructions for the different tasks that we discussed during the meeting.

**Comment by ChloeRN** [comment]
TASK 1: Implement uncertainty on all parameters in simplest model

In your current code, you are using a fixed number for starting population size, and a fixed number for the standard deviation of population growth rate. Instead, we want to use the distribution we obtained from the SCR model estimates. 
(This principle also applied to all the other implementations of the PVA; i.e. once we use vital rates, we have to specify the distributions for those accordingly).

**Comment by ChloeRN** [comment]
**TASK 2: Change to "Vital rates, no age structure" model, keep 2 year interval**

N[t+2] = N[t] * S[t] + N[t] * f[t] = N[t] * (S[t] + f[t])

**Comment by TaeKP** [comment]
Thank you very much for your summary.
These are really helpful to me, so I will proceed step by step and keep you posted on my progress.

**Comment by ChloeRN** [comment]
@TaeKP and @ndusit please check commit ce9fa38ef888692b7d2b8708f9bbd086bd669de0. 
I have added a note on how to set up the population model, and how to go from 2-year to 1-year, and from 1-year to age structure. 

Regarding the splitting into reproductive vital rates: I added some thoughts on that too. Bottom-line is that I cannot think of a good way to implement this with the setup we have now. 
I think this will have to wait for later, when we can maybe do a fully integrated Bayesian model (SCR and reproductive data). 
For now, I suggest shelving this and focusing on the PVA for Tae's paper.

**Comment by TaeKP** [comment]
Dear Dr. @ChloeRN 
I have now implemented the uncertainty (SD) in some parameters in the simple model, please visit [https://github.com/TaeKP/OpenCR_script/commit/2b6a8c1552a71043fbfce1210f1cfd4b7be24b8d](https://github.com/TaeKP/OpenCR_script/commit/2b6a8c1552a71043fbfce1210f1cfd4b7be24b8d)
However, I am not sure how to proceed with the uncertainty for the rest of the models.

Now, I am trying to work on the proportion between adults and juveniles as your suggestion.

**Comment by ChloeRN** [comment]
@TaeKP I have reviewed your code. Please check pull request #3 and commit history for details 👍 

Looks good so far! You'll see that I have included truncated distributions. This is to prevent sampling impossible values, such as negative population sizes, population growth rates, and reproductive rates, and survival probabilities beyond the range 0-1.

**Comment by ChloeRN** [comment]
Next, I would suggest doing the following: 

1) Write a function around the simulations with the 2-year vital rate model, 1-year vital rate model, and 1-year age-structured vital rate model (equivalent to the function "pva_simulation()" for the simple 2-year model. 

2) Run simulations with the 2-year and 1-year vital rate model

3) Estimate mean and standard deviation of "proportion of adults in the population" from the raw data. As # adults observed/ # individuals (adults + kittens) observed. For both all years and only latest year. Then use that mean and SD to sample values for the parameter "init_adultProp" and run simulations for the 1-year age-structured vital rate model.

**Comment by TaeKP** [comment]
Dear Dr. @ChloeRN 
Thank you very much for your review and revision of the code.
I have now merged the pull request, so I will keep working on the next step suggestion.

**Comment by TaeKP** [comment]
Hello Dr. @ChloeRN 
Happy New Year!

Sorry for the late response, I'm now in the field survey.
Currently, I have added the loop for the simulation for the 2-year and 1-year models, please visit and review on 8364cf4296a61f710c17d5da319c6d3cdf08154c

Also, I'm working on the adult proportion, which will be committed soon. 
Thank you for your help.

**Comment by TaeKP** [comment]
Dear Dr. @ChloeRN 

Please visit and review my editing code: 1f3e10e7cc4ad8faf4f9867df440fb00861fe591 
I have estimated the mean and standard deviation of "proportion of adults in the population" from the raw data. As well as run simulations for the 1-year age-structured vital rate model as followed from your suggestion step.

I appreciate your help.

**Comment by ChloeRN** [comment]
@TaeKP please check out #4, where I have reviewed your latest code.

**Comment by TaeKP** [comment]
Hello Dr. @ChloeRN 

Sorry for taking it very long time to commit.
Please find my commits 09d0d062faef5d0e630f37b7c64b546553a2ddd3 and review that, which includes the recalculation of adult proportion and some idea of sensitivity analysis.

I truly appreciate your help.
